logging:
    level:
        org:
            springframework:
                jdbc:
                    core: DEBUG
                    core.JdbcTemplate: DEBUG
                    core.StatementCreatorUtils: TRACE
spring:
    datasource:
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        init:
            mode: always
            platform: mysql
        password: kASe1QkIm5xQUZMF7cXo
        url: "jdbc:mysql://poc.cy57hfox1fy1.us-east-1.rds.amazonaws.com:3306/poc"
        username: "admin"
    jpa:
        database: mysql
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    devtools:
        add-properties: false
server:
    port: 5000