logging:
    level:
        org:
            springframework:
                jdbc:
                    core: DEBUG
                    core.JdbcTemplate: DEBUG
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-test-query: SELECT NOW();
            connection-timeout: 20000
            idle-timeout: 10000
            maximum-pool-size: 5
            minimum-idle: 2
            pool-name: springPocPool
        init:
            mode: always
            platform: mysql
        name: pocDB
        type: com.zaxxer.hikari.HikariDataSource
        url: ${SPRING_DATASOURCE_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        database: mysql
        generate-ddl: true
        hibernate:
#            ddl-auto: create-drop
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true
server:
    port:
        8080
<<<<<<< HEAD
app:
    jwt:
        secret: qwertyuiosdfghjk
        expiration: "864000000"
=======
    tomcat:
        uri-encoding=UTF-8:
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
app:
    security:
        jwt:
keycloak:
    server:
        contextPath: /auth
        adminUser:
            username: ${AUTH_USER}
            password: ${AUTH_PASS}
        realmImportFile: jwt-config.json
>>>>>>> autenticacaojwt
