logging:
    level:
        org:
            springframework:
                jdbc:
                    core: DEBUG
                    core.JdbcTemplate: DEBUG
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connection-test-query: SELECT NOW();
            connection-timeout: 20000 # 20s
            idle-timeout: 10000 # 10s
            maximum-pool-size: 5
            minimum-idle: 2
            pool-name: springPocPool
        init:
#            mode: always
            platform: mysql
        name: pocDB
        type: com.zaxxer.hikari.HikariDataSource
        url: ${SPRING_DATASOURCE_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    jpa:
        database: mysql
        generate-ddl: true
        hibernate:
#            ddl-auto: create-drop
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true
#    sql:
#        init:
#            continue-on-error: true
http:
    port: 8080
server:
    port:
        8443
    ssl:
        certificate: "classpath:keystore/public.crt"
        certificate-private-key: "classpath:keystore/privatekey.pem"
    http2:
        enabled: true
app:
    jwt:
        secret: qwertyuiosdfghjk
#        expiration: "10000"
        expiration: "864000000"
    tomcat:
        uri-encoding=UTF-8:
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    temp:
        path: "/opt/pdf"
springdoc:
    swagger-ui:
        path: "/api/swagger-ui/index.html"
api:
    version: "v0.0.1"
    description: "Interface de aplicação para sistema CertVet"
    server:
        url: "http://localhost:8080"